-- Example db insert example for creating a service subscription
INSERT INTO FIF_REQUEST VALUES ('TESTID-001', 'SLS', 'NOT_STARTED', 'addServiceSubscription', '', SYSDATE, 0, SYSDATE, NULL, NULL, 'testuser', NULL);
INSERT INTO FIF_REQUEST_PARAM VALUES ('TESTID-001', 'PRODUCT_SUBSCRIPTION_ID', 'TESTID001');
INSERT INTO FIF_REQUEST_PARAM VALUES ('TESTID-001', 'CUSTOMER_NUMBER', '123456789012');
INSERT INTO FIF_REQUEST_PARAM VALUES ('TESTID-001', 'SERVICE_CODE', 'V0134');
INSERT INTO FIF_REQUEST_PARAM VALUES ('TESTID-001', 'CREATE_CONTACT', 'Y');

