-- Example db insert example for modifying an account
INSERT INTO FIF_REQUEST VALUES ('TESTID-002', 'SLS', 'NOT_STARTED', 'modifyAccount', '', SYSDATE, 0, SYSDATE, NULL, NULL, 'testuser', NULL);
INSERT INTO FIF_REQUEST_PARAM VALUES ('TESTID-002', 'ACCOUNT_NUMBER', 'TESTID001');
INSERT INTO FIF_REQUEST_PARAM VALUES ('TESTID-002', 'CUSTOMER_NUMBER', '123456789012');
INSERT INTO FIF_REQUEST_PARAM VALUES ('TESTID-002', 'CREATE_CONTACT', 'Y');

