- Script for creating synonims for the XML_REQUEST and XML_REQUEST_VALUE table

CREATE PUBLIC SYNONYM XML_REQUEST FOR XML_REQUEST;
CREATE PUBLIC SYNONYM XML_REQUEST_VALUE FOR XML_REQUEST_VALUE;
CREATE PUBLIC SYNONYM XML_REQUEST_RESULT FOR XML_REQUEST_RESULT;
