- Script for creating indexes for the XML_REQUEST and XML_REQUEST_VALUE table

ALTER TABLE XML_REQUEST
ADD  ( CONSTRAINT XPKXML_REQUEST PRIMARY KEY (EXT_SYS_WO_ID));

CREATE INDEX XIE1XML_REQUEST ON XML_REQUEST
(
       WO_STATUS                      ASC
);

ALTER TABLE XML_REQUEST_VALUE
ADD  ( CONSTRAINT XPKXML_REQUEST_VALUE PRIMARY KEY (EXT_SYS_WO_ID, PARAM));

ALTER TABLE XML_REQUEST_VALUE
ADD  ( CONSTRAINT XML_REQUEST_VALUE_REQUEST FOREIGN KEY (EXT_SYS_WO_ID)
       REFERENCES XML_REQUEST
       ON DELETE CASCADE ) ;

ALTER TABLE XML_REQUEST_RESULT
ADD  (CONSTRAINT XPKXML_REQUEST_RESULT PRIMARY KEY (EXT_SYS_WO_ID, RETURN_PARAM));

ALTER TABLE XML_REQUEST_RESULT
ADD  (CONSTRAINT XML_REQUEST_RESULT FOREIGN KEY (EXT_SYS_WO_ID)
      REFERENCES XML_REQUEST
      ON DELETE CASCADE);
